### ISSUE TITLE
Open Babel Error  in ReadFile

### ISSUE THREAD

**Issue by hesam-a** [pren/poltype#36]
Hi all, I ran into this error, some of the baby jobs are done some are not, here's the error in the parent job,

*** Open Babel Error  in ReadFile
  Cannot read from 20_3_Index_0.mol
slurmstepd: error: Detected 6 oom-kill event(s) in step 1865807.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler. 

also when I tried to run the baby jobs manually, again ran into the same problem with the error source, tried different memory values as well

Traceback (most recent call last):
  File "/gpfs/home/ha18/softwares/poltype/PoltypeModules/poltype.py", line 1096, in <module>
    params=poltype.main()
  File "/gpfs/home/ha18/softwares/poltype/PoltypeModules/poltype.py", line 872, in main
    params= self.GenerateParameters()
  File "/gpfs/home/ha18/softwares/poltype/PoltypeModules/poltype.py", line 971, in GenerateParameters
    esp.SPForESP(self,optmol,mol)
  File "/gpfs/home/ha18/softwares/poltype/PoltypeModules/electrostaticpotential.py", line 353, in SPForESP
    finishedjobs,errorjobs=poltype.CallJobsSeriallyLocalHost(jobtooutputlog,False)
  File "/gpfs/home/ha18/softwares/poltype/PoltypeModules/poltype.py", line 684, in CallJobsSeriallyLocalHost
    self.call_subsystem(job,True,skiperrors)
  File "/gpfs/home/ha18/softwares/poltype/PoltypeModules/poltype.py", line 819, in call_subsystem
    raise ValueError("ERROR: " + cmdstr+' '+'path'+' = '+os.getcwd())
ValueError: ERROR: cd /gpfs/home/ha18/host/host_poltype_CW/Fragments/35_8_Index_0 && GAUSS_SCRDIR=/gpfs/home/ha18/scratch/gauss_scratch/Gau-35_8_Index_0 /gpfs/research/software/gaussian09/amd/g09.01/g09 35_8_Index_0-esp.com path = /gpfs/home/ha18/host/host_poltype_CW/Fragments/35_8_Index_0
slurmstepd: error: Detected 1 oom-kill event(s) in step 1924091.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.

**Comment by walkerbdev** [comment]
Hello,

We are not sure what is causing babel to complain in this instance and have not bothered to find out since everything downstream seems to work fine in our test cases with this error present in log file.
