### ISSUE TITLE
RuntimeWarning

### ISSUE THREAD

**Issue by ahmedo047** [pren/poltype#57]
Hi,

I get the following "RuntimeWarning" while running the POLTYPE to get the benzene parameters. Do you know how I can fix this warning/error? 

> python3 /home/user/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py poltype.ini
> 
> Calling: analyze.x /home/user/anaconda3/envs/poltype/poltype-poltype2/water.xyz -k /home/user/anaconda3/envs/poltype/poltype-poltype2/water.key e> version.out
> /home/user/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/electrostaticpotential.py:423: **RuntimeWarning:** invalid value encountered in double_scalars
>   ratio=np.abs(diff/qmdipole)

**benzene.sdf:**
```
t.pdb
 OpenBabel09282009253D

 12 12  0  0  0  0  0  0  0  0999 V2000
   16.7700   17.2300   15.9700 C   0  0  0  0  0  0  0  0  0  0  0  0
   17.8500   16.3200   16.2000 C   0  0  0  0  0  0  0  0  0  0  0  0
   18.4900   16.2100   17.4200 C   0  0  0  0  0  0  0  0  0  0  0  0
   17.9700   16.9700   18.4200 C   0  0  0  0  0  0  0  0  0  0  0  0
   16.8600   17.7800   18.3300 C   0  0  0  0  0  0  0  0  0  0  0  0
   16.2300   17.9200   17.0800 C   0  0  0  0  0  0  0  0  0  0  0  0
   16.3400   17.3000   14.9800 H   0  0  0  0  0  0  0  0  0  0  0  0
   18.2200   15.8500   15.2900 H   0  0  0  0  0  0  0  0  0  0  0  0
   19.3700   15.5900   17.3600 H   0  0  0  0  0  0  0  0  0  0  0  0
   18.5000   16.8900   19.3700 H   0  0  0  0  0  0  0  0  0  0  0  0
   16.4700   18.2800   19.2100 H   0  0  0  0  0  0  0  0  0  0  0  0
   15.3300   18.5100   16.9800 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0  0  0  0
  1  6  1  0  0  0  0
  2  3  1  0  0  0  0
  3  4  2  0  0  0  0
  4 10  1  0  0  0  0
  5  4  1  0  0  0  0
  5 11  1  0  0  0  0
  6  5  2  0  0  0  0
  7  1  1  0  0  0  0
  8  2  1  0  0  0  0
  9  3  1  0  0  0  0
 12  6  1  0  0  0  0
M  END
>  <TITLE>
    Gromacs Runs One Microsecond At Cannonball Speeds

>  <MODEL>
       1

$$$$
```

**poltype.ini:**
```
structure=benzene.sdf
numproc=6
maxmem=6GB
maxdisk=20GB
```

**Comment by walkerbdev** [comment]
hi please attach a folder with all files I will take a look.

- Brandon

**Comment by ahmedo047** [comment]
Here it is: 
[benzene.zip](https://github.com/pren/poltype/files/5448260/benzene.zip)

**Comment by walkerbdev** [comment]
Awesome thanks, the issue is that the qm dipole is 0, and we typically use relative error in QM, MM dipole as a measure of how bad parameters are. So this means the program was dividing by 0! The bug has been fixed.

**Comment by ahmedo047** [comment]
Hi,

Now it gives another error. I think there is still a bug?

```
python3 /home/user/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py poltype.ini
Poltype -- Polarizable atom typer of small molecules for the AMOEBA polarizable force field

Please cite:
Wu, J.C.; Chattree, G.; Ren, P.Y.; Automation of AMOEBA polarizable force field 
parameterization for small molecules. Theor Chem Acc. 

Version 2.3.0 February 2020

Copyright (c)  Johnny Wu, Gaurav Chattree, Brandon Walker, Matthew Harger and Pengyu Ren 2019

All Rights Reserved
##############################################################################################################

Calling: analyze.x /home/user/anaconda3/envs/poltype/poltype-poltype2/water.xyz -k /home/user/anaconda3/envs/poltype/poltype-poltype2/water.key e> version.out
no longer error /home/user/Desktop/test/poltype/benzene/benzene-opt.log
no longer error /home/user/Desktop/test/poltype/benzene/benzene-opt.log
no longer error /home/user/Desktop/test/poltype/benzene/benzene-opt.log
no longer error /home/user/Desktop/test/poltype/benzene/benzene-opt.log
no longer error benzene-opt.log
no longer error benzene-opt.log
no longer error benzene-opt.log
no longer error benzene-opt.log
no longer error benzene-opt.log
no longer error benzene-opt.log
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py", line 1219, in <module>
    params=poltype.main()
  File "/home/user/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py", line 930, in main
    params= self.GenerateParameters()
  File "/home/user/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py", line 1191, in GenerateParameters
    esp.CheckDipoleMoments(self,optmol)
  File "/home/user/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/electrostaticpotential.py", line 501, in CheckDipoleMoments
    raise ValueError('Relative error of '+str(ratio)+' for QMDipole '+str(qmdipole)+' and '+str(mmdipole)+' for MMDipole '+'is bigger than '+str(poltype.dipoletol)+' '+os.getcwd()) 
ValueError: Relative error of 0.25 for QMDipole 0.004 and 0.003 for MMDipole is bigger than 0.1 /home/user/Desktop/test/poltype/benzene
```

**Comment by walkerbdev** [comment]
Okay thanks for the report.

The MM and QM dipoles are very close (good thing). I am unable to reproduce
your particular case with benzene, however I have added an absolute
tolerance for comparing QM to MM dipoles as well as the relative error
tolerance.

- Brandon

**Comment by ahmedo047** [comment]
Thanks. Now POLTYPE doesn't give any error but there are still a few problems:
-It doesn't generate the `valence.prms` file.
-It doesn't print the torsion parameters at the end of `polytype.log` file. 
-`Fragments` folder is empty. I think the fragmentation protocol doesn't work.
-POLTYPE doesn't terminate.

**Comment by walkerbdev** [comment]
There is nothing to fragment in Benzene. All torsion is transferred. Valence.prms not needed, that was for if someone want to add new torsion to existing database. This has been added to comments of key file.
________________________________
