### ISSUE TITLE
Issues with SMARTS Database Parser 

### ISSUE THREAD

**Issue by mquevill** [pren/poltype#65]
I was trying to run the current `poltype2` branch with NO3-, and got the following error. It looks like it might be an unhandled case in `MatchAtomIndicesSMARTSToParameterSMARTS`, but I'm not familiar with the logic to help debug this. Input file: [no3.sdf.txt](https://github.com/pren/poltype/files/5638620/no3.sdf.txt)

```
Traceback (most recent call last):
  File "~/development/poltype/PoltypeModules/poltype.py", line 1275, in <module>
    params=poltype.main()
  File "~/development/poltype/PoltypeModules/poltype.py", line 965, in main
    params= self.GenerateParameters()
  File "~/development/poltype/PoltypeModules/poltype.py", line 1085, in GenerateParameters
    bondprmstotransferinfo,angleprmstotransferinfo,torsionprmstotransferinfo,strbndprmstotransferinfo,opbendprmstotransferinfo,vdwprmstotransferinfo,torsionsmissing,classkeytotorsionparametersguess=databaseparser.GrabSmallMoleculeAMOEBAParameters(self,optmol,mol,m)
  File "~/development/poltype/PoltypeModules/databaseparser.py", line 1832, in GrabSmallMoleculeAMOEBAParameters
    atomindicesforprmtoparametersmarts,atomindicesforprmtosmarts=MatchAtomIndicesSMARTSToParameterSMARTS(poltype,atomindicesforprmtosmartslist,parametersmartslist,mol)
  File "~/development/poltype/PoltypeModules/databaseparser.py", line 803, in MatchAtomIndicesSMARTSToParameterSMARTS
    listforprmtoparametersmarts,listforprmtosmarts=GrabBestMatch(poltype,parametersmartstomatchlen,parametersmartstosmartslist,listforprmtoparametersmarts,listforprmtosmarts,ls)
  File "~/development/poltype/PoltypeModules/databaseparser.py", line 876, in GrabBestMatch
    maxparametersmartsmatchlength=max(parametersmartstomatchlen.values())
ValueError: max() arg is an empty sequence
```

**Comment by mquevill** [comment]
I updated the packages in my Conda environment, and now I'm getting a different error, oddly enough. It seems to be something with the SMARTS matching system, but I'm not sure how I might fix this, based on the error message.

`ValueError: Missing SMARTS-Atom Order -> Tinker Description, Element entry for smarts [#8]~[*] and matching to parameter smarts [#8](-[H])(-[H]) for indices (1, 0)`

**Comment by walkerbdev** [comment]
Thank you, I will take a look in the morning.

**Comment by walkerbdev** [comment]
Fixed now.
Thanks
