### ISSUE TITLE
Testing fails with no method specified

### ISSUE THREAD

**Issue by mquevill** [pren/poltype#7]
In `README_HELP.MD`, it is mentioned that `test_poltype.py` can be run with no arguments. However, this ends up setting `method=None`, which throws a `TypeError`. I've copied the Traceback below:

```shell
$ python ~/git/poltype/PoltypeModules/test_poltype.py
Traceback (most recent call last):
  File "~/git/poltype/PoltypeModules/test_poltype.py", line 503, in <module>
    suite.addTest(TestPoltype(method,examplepath,dontremovetestcase))
  File "~/git/poltype/PoltypeModules/test_poltype.py", line 13, in __init__
    super(TestPoltype, self).__init__(method)
  File "~/.conda/envs/p4env/lib/python3.8/unittest/case.py", line 433, in __init__
    testMethod = getattr(self, methodName)
TypeError: getattr(): attribute name must be string
```

**Comment by pren** [comment]
We are fixing the test.
