### ISSUE TITLE
TypeError: iteration over a 0-d array

### ISSUE THREAD

**Issue by ahmedo047** [pren/poltype#77]
Hi,

Poltype gives the below error for the naphthalene molecule. Is it a bug in `databaseparser.py`? I attach all the input/output files of naphthalene:
[naphthalene.zip](https://github.com/pren/poltype/files/5834865/naphthalene.zip)

**Error:**
```
Calling: analyze.x /home/phy/anaconda3/envs/poltype/poltype-poltype2/VersionFiles/water.xyz -k /home/phy/anaconda3/envs/poltype/poltype-poltype2/VersionFiles/water.key e> version.out
Traceback (most recent call last):
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py", line 1412, in <module>
    poltype.main()
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py", line 1000, in main
    params= self.GenerateParameters()
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py", line 1224, in GenerateParameters
    missingvdwatomindices=databaseparser.ReadList(self,self.vdwmissingfilename)
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/databaseparser.py", line 1796, in ReadList
    for subls in ls:
TypeError: iteration over a 0-d array
```

**Comment by ahmedo047** [comment]
And it gives the below error for the phenol molecule. Here is all the files of it:
[phenol.zip](https://github.com/pren/poltype/files/5835704/phenol.zip)

```
Calling: analyze.x /home/phy/anaconda3/envs/poltype/poltype-poltype2/VersionFiles/water.xyz -k /home/phy/anaconda3/envs/poltype/poltype-poltype2/VersionFiles/water.key e> version.out
missingvdwatomindices [1, 10]
Traceback (most recent call last):
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py", line 1412, in <module>
    poltype.main()
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py", line 1000, in main
    params= self.GenerateParameters()
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py", line 1293, in GenerateParameters
    esp.ElectrostaticPotentialComparison(self)  
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/electrostaticpotential.py", line 342, in ElectrostaticPotentialComparison
    rmspdexists=CheckRMSPD(poltype)
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/electrostaticpotential.py", line 208, in CheckRMSPD
    raise ValueError(os.getcwd()+' '+'Warning: RMSPD of QM and MM optimized structures is high, RMSPD = '+str(RMSPD))
ValueError: /home/phy/Desktop/AMOEBA/test/poltype/phenol Warning: RMSPD of QM and MM optimized structures is high, RMSPD = 5.7508
```

**Comment by walkerbdev** [comment]
Thank you for the bug report.

The issue with phenol was using DFT as default for this molecule seemed to make the bond and angles not converge at all to reasonable values. We are using HF as default instead. Both bugs are resolved now.

**Comment by ahmedo047** [comment]
Hi,

I think there is still a bug in `databaseparser.py`. It gives the following error for naphthalene (I had attached the input files of naphthalene before).
```
Calling: analyze.x /home/phy/anaconda3/envs/poltype/poltype-poltype2/VersionFiles/water.xyz -k /home/phy/anaconda3/envs/poltype/poltype-poltype2/VersionFiles/water.key e> version.out
Traceback (most recent call last):
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py", line 1412, in <module>
    poltype.main()
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py", line 1000, in main
    params= self.GenerateParameters()
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/poltype.py", line 1224, in GenerateParameters
    missingvdwatomindices=databaseparser.ReadList(self,self.vdwmissingfilename)
  File "/home/phy/anaconda3/envs/poltype/poltype-poltype2/PoltypeModules/databaseparser.py", line 1803, in ReadList
    newls.append(subls.tolist())
AttributeError: 'int' object has no attribute 'tolist'
```

**Comment by walkerbdev** [comment]
Thank you,

Just fixed this, try again.
