### ISSUE TITLE
Attribute 'pcm' does not exist with use_gaus

### ISSUE THREAD

**Issue by mquevill** [pren/poltype#92]
When poltype tries to use only Gaussian (with `use_gaus`), it tries to call the `.pcm` attribute, which does not exist. In the case of a charged molecule, where it tries to use PCM, there should be a more helpful error message/handling for this case.

```
Traceback (most recent call last):
  File "/poltype/PoltypeModules/poltype.py", line 1665, in <module>
    poltype.main()
  File "/poltype/PoltypeModules/poltype.py", line 1047, in main
    params= self.GenerateParameters()
  File "/poltype/PoltypeModules/poltype.py", line 1423, in GenerateParameters
    optmol,error = opt.GeometryOPTWrapper(self,mol)
  File "/poltype/PoltypeModules/optimization.py", line 20, in GeometryOPTWrapper
    if poltype.pcm==True:
AttributeError: 'PolarizableTyper' object has no attribute 'pcm'
```

**Comment by walkerbdev** [comment]
whoops, this one slipped through the cracks. Troubles with having two different poltypes and copying updates from one to the other.
